// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.2
// LVGL version: 8.3.6
// Project name: WT32SC01Test1Squareline_Project

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////
short typedCode;
char strCode[6];



// SCREEN: ui_AlarmArmed
void ui_AlarmArmed_screen_init(void);
lv_obj_t *ui_AlarmArmed;
void ui_event_AAButton1( lv_event_t * e);
lv_obj_t *ui_AAButton1;
lv_obj_t *ui_AALabel1;
void ui_event_AAButton2( lv_event_t * e);
lv_obj_t *ui_AAButton2;
lv_obj_t *ui_AALabel2;
void ui_event_AAButton3( lv_event_t * e);
lv_obj_t *ui_AAButton3;
lv_obj_t *ui_AALabel3;
void ui_event_AAButton4( lv_event_t * e);
lv_obj_t *ui_AAButton4;
lv_obj_t *ui_AALabel4;
void ui_event_AAButton5( lv_event_t * e);
lv_obj_t *ui_AAButton5;
lv_obj_t *ui_AALabel5;
void ui_event_AAButton6( lv_event_t * e);
lv_obj_t *ui_AAButton6;
lv_obj_t *ui_AALabel6;
void ui_event_AAButton7( lv_event_t * e);
lv_obj_t *ui_AAButton7;
lv_obj_t *ui_AALabel7;
void ui_event_AAButton8( lv_event_t * e);
lv_obj_t *ui_AAButton8;
lv_obj_t *ui_AALabel8;
void ui_event_AAButton9( lv_event_t * e);
lv_obj_t *ui_AAButton9;
lv_obj_t *ui_AALabel9;
void ui_event_AAButtonClear( lv_event_t * e);
lv_obj_t *ui_AAButtonClear;
lv_obj_t *ui_AALabel10;
void ui_event_AAButton0( lv_event_t * e);
lv_obj_t *ui_AAButton0;
lv_obj_t *ui_AALabel0;
void ui_event_AAButtonEnter( lv_event_t * e);
lv_obj_t *ui_AAButtonEnter;
lv_obj_t *ui_AALabelEnter;
lv_obj_t *ui_AALabelAlarmActive;
lv_obj_t *ui_AALabelAlarmTrippedOn;
lv_obj_t *ui_AALabelAlarmTrippedOff;
lv_obj_t *ui_AALabelEnteredPasscode;


// // SCREEN: ui_AlarmSet
// void ui_AlarmSet_screen_init(void);
// lv_obj_t *ui_AlarmSet;
// void ui_event_ASButton1( lv_event_t * e);
// lv_obj_t *ui_ASButton1;
// lv_obj_t *ui_AALabel11;
// void ui_event_ASButton2( lv_event_t * e);
// lv_obj_t *ui_ASButton2;
// lv_obj_t *ui_AALabel12;
// void ui_event_ASButton3( lv_event_t * e);
// lv_obj_t *ui_ASButton3;
// lv_obj_t *ui_AALabel13;
// void ui_event_ASButton4( lv_event_t * e);
// lv_obj_t *ui_ASButton4;
// lv_obj_t *ui_AALabel14;
// void ui_event_ASButton5( lv_event_t * e);
// lv_obj_t *ui_ASButton5;
// lv_obj_t *ui_AALabel15;
// void ui_event_ASButton6( lv_event_t * e);
// lv_obj_t *ui_ASButton6;
// lv_obj_t *ui_AALabel16;
// void ui_event_ASButton7( lv_event_t * e);
// lv_obj_t *ui_ASButton7;
// lv_obj_t *ui_AALabel17;
// void ui_event_ASButton8( lv_event_t * e);
// lv_obj_t *ui_ASButton8;
// lv_obj_t *ui_AALabel18;
// void ui_event_ASButton9( lv_event_t * e);
// lv_obj_t *ui_ASButton9;
// lv_obj_t *ui_AALabel19;
// void ui_event_ASButtonClear( lv_event_t * e);
// lv_obj_t *ui_ASButtonClear;
// lv_obj_t *ui_AALabel20;
// void ui_event_ASButton0( lv_event_t * e);
// lv_obj_t *ui_ASButton0;
// lv_obj_t *ui_AALabel21;
// void ui_event_ASButtonEnter( lv_event_t * e);
// lv_obj_t *ui_ASButtonEnter;
// lv_obj_t *ui_AALabelEnter1;
// lv_obj_t *ui_ASLabelAlarmSet;
// lv_obj_t *ui_remove_AALabelAlarmTrippedOn1;
// lv_obj_t *ui_remove_AALabelAlarmTrippedOff1;
// lv_obj_t *ui_ASLabelEnteredPasscode;
// lv_obj_t *ui____initial_actions0;



// SCREEN: ui_AlarmSet
void ui_AlarmSet_screen_init(void);
lv_obj_t *ui_AlarmSet;
void ui_event_ASButton1( lv_event_t * e);
lv_obj_t *ui_ASButton1;
lv_obj_t *ui_AALabel11;
void ui_event_ASButton2( lv_event_t * e);
lv_obj_t *ui_ASButton2;
lv_obj_t *ui_AALabel12;
void ui_event_ASButton3( lv_event_t * e);
lv_obj_t *ui_ASButton3;
lv_obj_t *ui_AALabel13;
void ui_event_ASButton4( lv_event_t * e);
lv_obj_t *ui_ASButton4;
lv_obj_t *ui_AALabel14;
void ui_event_ASButton5( lv_event_t * e);
lv_obj_t *ui_ASButton5;
lv_obj_t *ui_AALabel15;
void ui_event_ASButton6( lv_event_t * e);
lv_obj_t *ui_ASButton6;
lv_obj_t *ui_AALabel16;
void ui_event_ASButton7( lv_event_t * e);
lv_obj_t *ui_ASButton7;
lv_obj_t *ui_AALabel17;
void ui_event_ASButton8( lv_event_t * e);
lv_obj_t *ui_ASButton8;
lv_obj_t *ui_AALabel18;
void ui_event_ASButton9( lv_event_t * e);
lv_obj_t *ui_ASButton9;
lv_obj_t *ui_AALabel19;
void ui_event_ASButtonClear( lv_event_t * e);
lv_obj_t *ui_ASButtonClear;
lv_obj_t *ui_AALabel20;
void ui_event_ASButton0( lv_event_t * e);
lv_obj_t *ui_ASButton0;
lv_obj_t *ui_AALabel21;
void ui_event_ASButtonEnter( lv_event_t * e);
lv_obj_t *ui_ASButtonEnter;
lv_obj_t *ui_AALabelEnter1;
lv_obj_t *ui_ASLabelAlarmSetTop;
lv_obj_t *ui_remove_AALabelAlarmTrippedOn1;
lv_obj_t *ui_remove_AALabelAlarmTrippedOff1;
lv_obj_t *ui_ASLabelEnteredPasscode;
lv_obj_t *ui_ASPanelScanLine;
lv_obj_t *ui_ASLabelEnterNewGuestCode;
lv_obj_t *ui_ASLabelEnterNewGuestCode1;
void ui_event_ASButtonBack( lv_event_t * e);
lv_obj_t *ui_ASButtonBack;
lv_obj_t *ui_ASBack;


// SCREEN: ui_ChooseCode
void ui_ChooseCode_screen_init(void);
lv_obj_t *ui_ChooseCode;
void ui_event_CCButtonAdmin( lv_event_t * e);
lv_obj_t *ui_CCButtonAdmin;
lv_obj_t *ui_CCLabelAdmin;
void ui_event_CCButtonGuest1( lv_event_t * e);
lv_obj_t *ui_CCButtonGuest1;
lv_obj_t *ui_CCLabelGuest1;
void ui_event_CCButtonGuest2( lv_event_t * e);
lv_obj_t *ui_CCButtonGuest2;
lv_obj_t *ui_CCLabelGuest2;
void ui_event_CCButtonBack( lv_event_t * e);
lv_obj_t *ui_CCButtonBack;
lv_obj_t *ui_CCBack;
lv_obj_t *ui_CCLabelChoseCode;
lv_obj_t *ui_CCLabelChooseCode;
lv_obj_t *ui_remove_CCLabelEnterNewGuestCode3;


// SCREEN: ui_MainMenu
void ui_MainMenu_screen_init(void);
lv_obj_t *ui_MainMenu;
void ui_event_MMButtonSetAlarm( lv_event_t * e);
lv_obj_t *ui_MMButtonSetAlarm;
lv_obj_t *ui_MMLabelSetAlarm;
void ui_event_MMButtonSettings( lv_event_t * e);
lv_obj_t *ui_MMButtonSettings;
lv_obj_t *ui_MMLabelSettings;
void ui_event_MMButtonChangeCode( lv_event_t * e);
lv_obj_t *ui_MMButtonChangeCode;
lv_obj_t *ui_MMLabelChangeCode;
void ui_event_MMButtonBack( lv_event_t * e);
lv_obj_t *ui_MMButtonBack;
lv_obj_t *ui_MMBack;
lv_obj_t *ui_MMLabelMenu;
lv_obj_t *ui_removeCCLabelChooseCode1;
lv_obj_t *ui_remove_CCLabelEnterNewGuestCode1;
lv_obj_t *ui____initial_actions0;





///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=1
    #error "LV_COLOR_16_SWAP should be 1 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////
void ui_event_AAButton1( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      AAButtonPressed1( e );
}
}
void ui_event_AAButton2( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      AAButtonPressed2( e );
}
}
void ui_event_AAButton3( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      AAButtonPressed3( e );
}
}
void ui_event_AAButton4( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      AAButtonPressed4( e );
}
}
void ui_event_AAButton5( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      AAButtonPressed5( e );
}
}
void ui_event_AAButton6( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      AAButtonPressed6( e );
}
}
void ui_event_AAButton7( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      AAButtonPressed7( e );
}
}
void ui_event_AAButton8( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      AAButtonPressed8( e );
}
}
void ui_event_AAButton9( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      AAButtonPressed9( e );
}
}
void ui_event_AAButtonClear( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      AAButtonPressedClear( e );
}
}
void ui_event_AAButton0( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      AAButtonPressed0( e );
}
}
void ui_event_AAButtonEnter( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      AAButtonPressedEnter( e );
}
}
void ui_event_ASButton1( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      ASButtonPressed1( e );
}
}
void ui_event_ASButton2( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      ASButtonPressed2( e );
}
}
void ui_event_ASButton3( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      ASButtonPressed3( e );
}
}
void ui_event_ASButton4( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      ASButtonPressed4( e );
}
}
void ui_event_ASButton5( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      ASButtonPressed5( e );
}
}
void ui_event_ASButton6( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      ASButtonPressed6( e );
}
}
void ui_event_ASButton7( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      ASButtonPressed7( e );
}
}
void ui_event_ASButton8( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      ASButtonPressed8( e );
}
}
void ui_event_ASButton9( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      ASButtonPressed9( e );
}
}
void ui_event_ASButtonClear( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      ASButtonPressedClear( e );
}
}
void ui_event_ASButton0( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      ASButtonPressed0( e );
}
}
void ui_event_ASButtonEnter( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      ASButtonPressedEnter( e );
}
}
void ui_event_ASButtonBack( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      ASButtonPressedBack( e );
}
}
void ui_event_CCButtonAdmin( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      CCButtonPressedAdmin( e );
}
}
void ui_event_CCButtonGuest1( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      CCButtonPressedGuest1( e );
}
}
void ui_event_CCButtonGuest2( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      CCButtonPressedGuest2( e );
}
}
void ui_event_CCButtonBack( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      CCButtonPressedBack( e );
}
}
void ui_event_MMButtonSetAlarm( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      MMButtonPressedSetAlarm( e );
}
}
void ui_event_MMButtonSettings( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      MMButtonPressedSettings( e );
}
}
void ui_event_MMButtonChangeCode( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      MMButtonPressedEditCode( e );
}
}
void ui_event_MMButtonBack( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      MMButtonPressedBack( e );
}
}
///////////////////// SCREENS ////////////////////



void ui_init( void )
{
lv_disp_t *dispp = lv_disp_get_default();
lv_theme_t *theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED), false, LV_FONT_DEFAULT);
lv_disp_set_theme(dispp, theme);
ui_AlarmArmed_screen_init();
ui_AlarmSet_screen_init();
ui_ChooseCode_screen_init();
ui_MainMenu_screen_init();
ui____initial_actions0 = lv_obj_create(NULL);
//lv_disp_load_scr( ui_AlarmSet);// ui_AlarmArmed);


lv_obj_clean(lv_scr_act());
//lv_obj_t * screen;
//screen = lv_obj_create(NULL, NULL);
lv_scr_load(ui_AlarmSet);//screen);
lv_indev_wait_release(lv_indev_get_act());
//lv_obj_t * cont = lv_cont_create(ui_AlarmSet, NULL);

}
