// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.2
// LVGL version: 8.3.6
// Project name: WT32SC01Test1Squareline_Project

#ifndef _WT32SC01Test1Squareline_PROJECT_UI_H
#define _WT32SC01Test1Squareline_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

    #include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"
// // SCREEN: ui_AlarmArmed
// void ui_AlarmArmed_screen_init(void);
// extern lv_obj_t *ui_AlarmArmed;
// void ui_event_AAButton1( lv_event_t * e);
// extern lv_obj_t *ui_AAButton1;
// extern lv_obj_t *ui_AALabel1;
// void ui_event_AAButton2( lv_event_t * e);
// extern lv_obj_t *ui_AAButton2;
// extern lv_obj_t *ui_AALabel2;
// void ui_event_AAButton3( lv_event_t * e);
// extern lv_obj_t *ui_AAButton3;
// extern lv_obj_t *ui_AALabel3;
// void ui_event_AAButton4( lv_event_t * e);
// extern lv_obj_t *ui_AAButton4;
// extern lv_obj_t *ui_AALabel4;
// void ui_event_AAButton5( lv_event_t * e);
// extern lv_obj_t *ui_AAButton5;
// extern lv_obj_t *ui_AALabel5;
// void ui_event_AAButton6( lv_event_t * e);
// extern lv_obj_t *ui_AAButton6;
// extern lv_obj_t *ui_AALabel6;
// void ui_event_AAButton7( lv_event_t * e);
// extern lv_obj_t *ui_AAButton7;
// extern lv_obj_t *ui_AALabel7;
// void ui_event_AAButton8( lv_event_t * e);
// extern lv_obj_t *ui_AAButton8;
// extern lv_obj_t *ui_AALabel8;
// void ui_event_AAButton9( lv_event_t * e);
// extern lv_obj_t *ui_AAButton9;
// extern lv_obj_t *ui_AALabel9;
// void ui_event_AAButtonClear( lv_event_t * e);
// extern lv_obj_t *ui_AAButtonClear;
// extern lv_obj_t *ui_AALabel10;
// void ui_event_AAButton0( lv_event_t * e);
// extern lv_obj_t *ui_AAButton0;
// extern lv_obj_t *ui_AALabel0;
// void ui_event_AAButtonEnter( lv_event_t * e);
// extern lv_obj_t *ui_AAButtonEnter;
// extern lv_obj_t *ui_AALabelEnter;
// extern lv_obj_t *ui_AALabelAlarmActive;
// extern lv_obj_t *ui_AALabelAlarmTrippedOn;
// extern lv_obj_t *ui_AALabelAlarmTrippedOff;
// extern lv_obj_t *ui_AALabelEnteredPasscode;
// // SCREEN: ui_AlarmSet
// void ui_AlarmSet_screen_init(void);
// extern lv_obj_t *ui_AlarmSet;
// void ui_event_ASButton1( lv_event_t * e);
// extern lv_obj_t *ui_ASButton1;
// extern lv_obj_t *ui_AALabel11;
// void ui_event_ASButton2( lv_event_t * e);
// extern lv_obj_t *ui_ASButton2;
// extern lv_obj_t *ui_AALabel12;
// void ui_event_ASButton3( lv_event_t * e);
// extern lv_obj_t *ui_ASButton3;
// extern lv_obj_t *ui_AALabel13;
// void ui_event_ASButton4( lv_event_t * e);
// extern lv_obj_t *ui_ASButton4;
// extern lv_obj_t *ui_AALabel14;
// void ui_event_ASButton5( lv_event_t * e);
// extern lv_obj_t *ui_ASButton5;
// extern lv_obj_t *ui_AALabel15;
// void ui_event_ASButton6( lv_event_t * e);
// extern lv_obj_t *ui_ASButton6;
// extern lv_obj_t *ui_AALabel16;
// void ui_event_ASButton7( lv_event_t * e);
// extern lv_obj_t *ui_ASButton7;
// extern lv_obj_t *ui_AALabel17;
// void ui_event_ASButton8( lv_event_t * e);
// extern lv_obj_t *ui_ASButton8;
// extern lv_obj_t *ui_AALabel18;
// void ui_event_ASButton9( lv_event_t * e);
// extern lv_obj_t *ui_ASButton9;
// extern lv_obj_t *ui_AALabel19;
// void ui_event_ASButtonClear( lv_event_t * e);
// extern lv_obj_t *ui_ASButtonClear;
// extern lv_obj_t *ui_AALabel20;
// void ui_event_ASButton0( lv_event_t * e);
// extern lv_obj_t *ui_ASButton0;
// extern lv_obj_t *ui_AALabel21;
// void ui_event_ASButtonEnter( lv_event_t * e);
// extern lv_obj_t *ui_ASButtonEnter;
// extern lv_obj_t *ui_AALabelEnter1;
// extern lv_obj_t *ui_ASLabelAlarmSet;
// extern lv_obj_t *ui_remove_AALabelAlarmTrippedOn1;
// extern lv_obj_t *ui_remove_AALabelAlarmTrippedOff1;
// extern lv_obj_t *ui_ASLabelEnteredPasscode;
// extern lv_obj_t *ui____initial_actions0;






// SCREEN: ui_AlarmArmed
void ui_AlarmArmed_screen_init(void);
extern lv_obj_t *ui_AlarmArmed;
void ui_event_AAButton1( lv_event_t * e);
extern lv_obj_t *ui_AAButton1;
extern lv_obj_t *ui_AALabel1;
void ui_event_AAButton2( lv_event_t * e);
extern lv_obj_t *ui_AAButton2;
extern lv_obj_t *ui_AALabel2;
void ui_event_AAButton3( lv_event_t * e);
extern lv_obj_t *ui_AAButton3;
extern lv_obj_t *ui_AALabel3;
void ui_event_AAButton4( lv_event_t * e);
extern lv_obj_t *ui_AAButton4;
extern lv_obj_t *ui_AALabel4;
void ui_event_AAButton5( lv_event_t * e);
extern lv_obj_t *ui_AAButton5;
extern lv_obj_t *ui_AALabel5;
void ui_event_AAButton6( lv_event_t * e);
extern lv_obj_t *ui_AAButton6;
extern lv_obj_t *ui_AALabel6;
void ui_event_AAButton7( lv_event_t * e);
extern lv_obj_t *ui_AAButton7;
extern lv_obj_t *ui_AALabel7;
void ui_event_AAButton8( lv_event_t * e);
extern lv_obj_t *ui_AAButton8;
extern lv_obj_t *ui_AALabel8;
void ui_event_AAButton9( lv_event_t * e);
extern lv_obj_t *ui_AAButton9;
extern lv_obj_t *ui_AALabel9;
void ui_event_AAButtonClear( lv_event_t * e);
extern lv_obj_t *ui_AAButtonClear;
extern lv_obj_t *ui_AALabel10;
void ui_event_AAButton0( lv_event_t * e);
extern lv_obj_t *ui_AAButton0;
extern lv_obj_t *ui_AALabel0;
void ui_event_AAButtonEnter( lv_event_t * e);
extern lv_obj_t *ui_AAButtonEnter;
extern lv_obj_t *ui_AALabelEnter;
extern lv_obj_t *ui_AALabelAlarmActive;
extern lv_obj_t *ui_AALabelAlarmTrippedOn;
extern lv_obj_t *ui_AALabelAlarmTrippedOff;
extern lv_obj_t *ui_AALabelEnteredPasscode;
// SCREEN: ui_AlarmSet
void ui_AlarmSet_screen_init(void);
extern lv_obj_t *ui_AlarmSet;
void ui_event_ASButton1( lv_event_t * e);
extern lv_obj_t *ui_ASButton1;
extern lv_obj_t *ui_AALabel11;
void ui_event_ASButton2( lv_event_t * e);
extern lv_obj_t *ui_ASButton2;
extern lv_obj_t *ui_AALabel12;
void ui_event_ASButton3( lv_event_t * e);
extern lv_obj_t *ui_ASButton3;
extern lv_obj_t *ui_AALabel13;
void ui_event_ASButton4( lv_event_t * e);
extern lv_obj_t *ui_ASButton4;
extern lv_obj_t *ui_AALabel14;
void ui_event_ASButton5( lv_event_t * e);
extern lv_obj_t *ui_ASButton5;
extern lv_obj_t *ui_AALabel15;
void ui_event_ASButton6( lv_event_t * e);
extern lv_obj_t *ui_ASButton6;
extern lv_obj_t *ui_AALabel16;
void ui_event_ASButton7( lv_event_t * e);
extern lv_obj_t *ui_ASButton7;
extern lv_obj_t *ui_AALabel17;
void ui_event_ASButton8( lv_event_t * e);
extern lv_obj_t *ui_ASButton8;
extern lv_obj_t *ui_AALabel18;
void ui_event_ASButton9( lv_event_t * e);
extern lv_obj_t *ui_ASButton9;
extern lv_obj_t *ui_AALabel19;
void ui_event_ASButtonClear( lv_event_t * e);
extern lv_obj_t *ui_ASButtonClear;
extern lv_obj_t *ui_AALabel20;
void ui_event_ASButton0( lv_event_t * e);
extern lv_obj_t *ui_ASButton0;
extern lv_obj_t *ui_AALabel21;
void ui_event_ASButtonEnter( lv_event_t * e);
extern lv_obj_t *ui_ASButtonEnter;
extern lv_obj_t *ui_AALabelEnter1;
extern lv_obj_t *ui_ASLabelAlarmSetTop;
extern lv_obj_t *ui_remove_AALabelAlarmTrippedOn1;
extern lv_obj_t *ui_remove_AALabelAlarmTrippedOff1;
extern lv_obj_t *ui_ASLabelEnteredPasscode;
extern lv_obj_t *ui_ASPanelScanLine;
extern lv_obj_t *ui_ASLabelEnterNewGuestCode;
extern lv_obj_t *ui_ASLabelEnterNewGuestCode1;
void ui_event_ASButtonBack( lv_event_t * e);
extern lv_obj_t *ui_ASButtonBack;
extern lv_obj_t *ui_ASBack;
// SCREEN: ui_ChooseCode
void ui_ChooseCode_screen_init(void);
extern lv_obj_t *ui_ChooseCode;
void ui_event_CCButtonAdmin( lv_event_t * e);
extern lv_obj_t *ui_CCButtonAdmin;
extern lv_obj_t *ui_CCLabelAdmin;
void ui_event_CCButtonGuest1( lv_event_t * e);
extern lv_obj_t *ui_CCButtonGuest1;
extern lv_obj_t *ui_CCLabelGuest1;
void ui_event_CCButtonGuest2( lv_event_t * e);
extern lv_obj_t *ui_CCButtonGuest2;
extern lv_obj_t *ui_CCLabelGuest2;
void ui_event_CCButtonBack( lv_event_t * e);
extern lv_obj_t *ui_CCButtonBack;
extern lv_obj_t *ui_CCBack;
extern lv_obj_t *ui_CCLabelChoseCode;
extern lv_obj_t *ui_CCLabelChooseCode;
extern lv_obj_t *ui_remove_CCLabelEnterNewGuestCode3;
// SCREEN: ui_MainMenu
void ui_MainMenu_screen_init(void);
extern lv_obj_t *ui_MainMenu;
void ui_event_MMButtonSetAlarm( lv_event_t * e);
extern lv_obj_t *ui_MMButtonSetAlarm;
extern lv_obj_t *ui_MMLabelSetAlarm;
void ui_event_MMButtonSettings( lv_event_t * e);
extern lv_obj_t *ui_MMButtonSettings;
extern lv_obj_t *ui_MMLabelSettings;
void ui_event_MMButtonChangeCode( lv_event_t * e);
extern lv_obj_t *ui_MMButtonChangeCode;
extern lv_obj_t *ui_MMLabelChangeCode;
void ui_event_MMButtonBack( lv_event_t * e);
extern lv_obj_t *ui_MMButtonBack;
extern lv_obj_t *ui_MMBack;
extern lv_obj_t *ui_MMLabelMenu;
extern lv_obj_t *ui_removeCCLabelChooseCode1;
extern lv_obj_t *ui_remove_CCLabelEnterNewGuestCode1;
extern lv_obj_t *ui____initial_actions0;









extern short typedCode;
extern char strCode[6];


void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
