// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.2
// LVGL version: 8.3.6
// Project name: WT32SC01Test1Squareline_Project

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void AAButtonPressed1(lv_event_t * e);
void AAButtonPressed2(lv_event_t * e);
void AAButtonPressed3(lv_event_t * e);
void AAButtonPressed4(lv_event_t * e);
void AAButtonPressed5(lv_event_t * e);
void AAButtonPressed6(lv_event_t * e);
void AAButtonPressed7(lv_event_t * e);
void AAButtonPressed8(lv_event_t * e);
void AAButtonPressed9(lv_event_t * e);
void AAButtonPressedClear(lv_event_t * e);
void AAButtonPressed0(lv_event_t * e);
void AAButtonPressedEnter(lv_event_t * e);
void ASButtonPressed1(lv_event_t * e);
void ASButtonPressed2(lv_event_t * e);
void ASButtonPressed3(lv_event_t * e);
void ASButtonPressed4(lv_event_t * e);
void ASButtonPressed5(lv_event_t * e);
void ASButtonPressed6(lv_event_t * e);
void ASButtonPressed7(lv_event_t * e);
void ASButtonPressed8(lv_event_t * e);
void ASButtonPressed9(lv_event_t * e);
void ASButtonPressedClear(lv_event_t * e);
void ASButtonPressed0(lv_event_t * e);
void ASButtonPressedEnter(lv_event_t * e);
void ASButtonPressedBack(lv_event_t * e);
void CCButtonPressedAdmin(lv_event_t * e);
void CCButtonPressedGuest1(lv_event_t * e);
void CCButtonPressedGuest2(lv_event_t * e);
void CCButtonPressedBack(lv_event_t * e);
void MMButtonPressedSetAlarm(lv_event_t * e);
void MMButtonPressedSettings(lv_event_t * e);
void MMButtonPressedEditCode(lv_event_t * e);
void MMButtonPressedBack(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
