// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.2
// LVGL version: 8.3.6
// Project name: WT32SC01Test1Squareline_Project

#include "ui.h"

void AAButtonPressed1(lv_event_t * e)
{
	shift_OGvalue_by_10_add_NEWvalue(1);
}

void AAButtonPressed2(lv_event_t * e)
{
	shift_OGvalue_by_10_add_NEWvalue(2);
}

void AAButtonPressed3(lv_event_t * e)
{
	shift_OGvalue_by_10_add_NEWvalue(3);
}

void AAButtonPressed4(lv_event_t * e)
{
	shift_OGvalue_by_10_add_NEWvalue(4);
}

void AAButtonPressed5(lv_event_t * e)
{
	shift_OGvalue_by_10_add_NEWvalue(5);
}

void AAButtonPressed6(lv_event_t * e)
{
	shift_OGvalue_by_10_add_NEWvalue(6);
}

void AAButtonPressed7(lv_event_t * e)
{
	shift_OGvalue_by_10_add_NEWvalue(7);
}

void AAButtonPressed8(lv_event_t * e)
{
	shift_OGvalue_by_10_add_NEWvalue(8);
}

void AAButtonPressed9(lv_event_t * e)
{
	shift_OGvalue_by_10_add_NEWvalue(9);
}

void AAButtonPressedClear(lv_event_t * e)
{
	typedCode = 0;
	//strCode;// = "";
}

void AAButtonPressed0(lv_event_t * e)
{
	shift_OGvalue_by_10_add_NEWvalue(0);
}

void AAButtonPressedEnter(lv_event_t * e)
{
	testCheckTypedCode(0);
}

void ASButtonPressed1(lv_event_t * e)
{
	shift_OGvalue_by_10_add_NEWvalue(1);
}

void ASButtonPressed2(lv_event_t * e)
{
	shift_OGvalue_by_10_add_NEWvalue(2);
}

void ASButtonPressed3(lv_event_t * e)
{
	shift_OGvalue_by_10_add_NEWvalue(3);
}

void ASButtonPressed4(lv_event_t * e)
{
	shift_OGvalue_by_10_add_NEWvalue(4);
}

void ASButtonPressed5(lv_event_t * e)
{
	shift_OGvalue_by_10_add_NEWvalue(5);
}

void ASButtonPressed6(lv_event_t * e)
{
	shift_OGvalue_by_10_add_NEWvalue(6);
}

void ASButtonPressed7(lv_event_t * e)
{
	shift_OGvalue_by_10_add_NEWvalue(7);
}

void ASButtonPressed8(lv_event_t * e)
{
	shift_OGvalue_by_10_add_NEWvalue(8);
}

void ASButtonPressed9(lv_event_t * e)
{
	shift_OGvalue_by_10_add_NEWvalue(9);
}

void ASButtonPressedClear(lv_event_t * e)
{
	typedCode = 0;
	//strCode = "";
}

void ASButtonPressed0(lv_event_t * e)
{
	shift_OGvalue_by_10_add_NEWvalue(0);
}

void ASButtonPressedEnter(lv_event_t * e)
{
	testCheckTypedCode(1);	
}
void ASButtonPressedBack(lv_event_t * e)
{
	// Your code here
}

void CCButtonPressedAdmin(lv_event_t * e)
{
	// Your code here
}

void CCButtonPressedGuest1(lv_event_t * e)
{
	// Your code here
}

void CCButtonPressedGuest2(lv_event_t * e)
{
	// Your code here
}

void CCButtonPressedBack(lv_event_t * e)
{
	// Your code here
}

void MMButtonPressedSetAlarm(lv_event_t * e)
{
	// Your code here
}

void MMButtonPressedSettings(lv_event_t * e)
{
	// Your code here
}

void MMButtonPressedEditCode(lv_event_t * e)
{
	// Your code here
}

void MMButtonPressedBack(lv_event_t * e)
{
	// Your code here
}
