// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.2
// LVGL version: 8.3.6
// Project name: wt32-sc01-test1-SquareLine_Project

#include "../ui.h"

void ui_AlarmArmed_screen_init(void)
{
ui_AlarmArmed = lv_obj_create(NULL);
lv_obj_clear_flag( ui_AlarmArmed, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_AlarmArmed, lv_color_hex(0x200000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_AlarmArmed, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_AAButton1 = lv_btn_create(ui_AlarmArmed);
lv_obj_set_width( ui_AAButton1, 80);
lv_obj_set_height( ui_AAButton1, 80);
lv_obj_set_x( ui_AAButton1, -90 );
lv_obj_set_y( ui_AAButton1, 48 );
lv_obj_set_align( ui_AAButton1, LV_ALIGN_TOP_MID );
lv_obj_add_flag( ui_AAButton1, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_AAButton1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_AAButton1, lv_color_hex(0xFFFF00), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_AAButton1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_AALabel1 = lv_label_create(ui_AAButton1);
lv_obj_set_width( ui_AALabel1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_AALabel1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_AALabel1, LV_ALIGN_CENTER );
lv_label_set_text(ui_AALabel1,"1");
lv_obj_set_style_text_color(ui_AALabel1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_AALabel1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_AALabel1, &lv_font_montserrat_48, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_AAButton2 = lv_btn_create(ui_AlarmArmed);
lv_obj_set_width( ui_AAButton2, 80);
lv_obj_set_height( ui_AAButton2, 80);
lv_obj_set_x( ui_AAButton2, 0 );
lv_obj_set_y( ui_AAButton2, 48 );
lv_obj_set_align( ui_AAButton2, LV_ALIGN_TOP_MID );
lv_obj_add_flag( ui_AAButton2, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_AAButton2, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_AAButton2, lv_color_hex(0xFFFF00), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_AAButton2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_AALabel2 = lv_label_create(ui_AAButton2);
lv_obj_set_width( ui_AALabel2, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_AALabel2, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_AALabel2, LV_ALIGN_CENTER );
lv_label_set_text(ui_AALabel2,"2");
lv_obj_set_style_text_color(ui_AALabel2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_AALabel2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_AALabel2, &lv_font_montserrat_48, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_AAButton3 = lv_btn_create(ui_AlarmArmed);
lv_obj_set_width( ui_AAButton3, 80);
lv_obj_set_height( ui_AAButton3, 80);
lv_obj_set_x( ui_AAButton3, 90 );
lv_obj_set_y( ui_AAButton3, 48 );
lv_obj_set_align( ui_AAButton3, LV_ALIGN_TOP_MID );
lv_obj_add_flag( ui_AAButton3, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_AAButton3, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_AAButton3, lv_color_hex(0xFFFF00), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_AAButton3, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_AALabel3 = lv_label_create(ui_AAButton3);
lv_obj_set_width( ui_AALabel3, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_AALabel3, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_AALabel3, LV_ALIGN_CENTER );
lv_label_set_text(ui_AALabel3,"3");
lv_obj_set_style_text_color(ui_AALabel3, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_AALabel3, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_AALabel3, &lv_font_montserrat_48, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_AAButton4 = lv_btn_create(ui_AlarmArmed);
lv_obj_set_width( ui_AAButton4, 80);
lv_obj_set_height( ui_AAButton4, 80);
lv_obj_set_x( ui_AAButton4, -90 );
lv_obj_set_y( ui_AAButton4, 133 );
lv_obj_set_align( ui_AAButton4, LV_ALIGN_TOP_MID );
lv_obj_add_flag( ui_AAButton4, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_AAButton4, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_AAButton4, lv_color_hex(0xFFFF00), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_AAButton4, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_AALabel4 = lv_label_create(ui_AAButton4);
lv_obj_set_width( ui_AALabel4, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_AALabel4, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_AALabel4, LV_ALIGN_CENTER );
lv_label_set_text(ui_AALabel4,"4");
lv_obj_set_style_text_color(ui_AALabel4, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_AALabel4, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_AALabel4, &lv_font_montserrat_48, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_AAButton5 = lv_btn_create(ui_AlarmArmed);
lv_obj_set_width( ui_AAButton5, 80);
lv_obj_set_height( ui_AAButton5, 80);
lv_obj_set_x( ui_AAButton5, 0 );
lv_obj_set_y( ui_AAButton5, 133 );
lv_obj_set_align( ui_AAButton5, LV_ALIGN_TOP_MID );
lv_obj_add_flag( ui_AAButton5, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_AAButton5, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_AAButton5, lv_color_hex(0xFFFF00), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_AAButton5, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_AALabel5 = lv_label_create(ui_AAButton5);
lv_obj_set_width( ui_AALabel5, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_AALabel5, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_AALabel5, LV_ALIGN_CENTER );
lv_label_set_text(ui_AALabel5,"5");
lv_obj_set_style_text_color(ui_AALabel5, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_AALabel5, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_AALabel5, &lv_font_montserrat_48, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_AAButton6 = lv_btn_create(ui_AlarmArmed);
lv_obj_set_width( ui_AAButton6, 80);
lv_obj_set_height( ui_AAButton6, 80);
lv_obj_set_x( ui_AAButton6, 90 );
lv_obj_set_y( ui_AAButton6, 133 );
lv_obj_set_align( ui_AAButton6, LV_ALIGN_TOP_MID );
lv_obj_add_flag( ui_AAButton6, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_AAButton6, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_AAButton6, lv_color_hex(0xFFFF00), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_AAButton6, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_AALabel6 = lv_label_create(ui_AAButton6);
lv_obj_set_width( ui_AALabel6, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_AALabel6, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_AALabel6, LV_ALIGN_CENTER );
lv_label_set_text(ui_AALabel6,"6");
lv_obj_set_style_text_color(ui_AALabel6, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_AALabel6, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_AALabel6, &lv_font_montserrat_48, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_AAButton7 = lv_btn_create(ui_AlarmArmed);
lv_obj_set_width( ui_AAButton7, 80);
lv_obj_set_height( ui_AAButton7, 80);
lv_obj_set_x( ui_AAButton7, -90 );
lv_obj_set_y( ui_AAButton7, 218 );
lv_obj_set_align( ui_AAButton7, LV_ALIGN_TOP_MID );
lv_obj_add_flag( ui_AAButton7, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_AAButton7, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_AAButton7, lv_color_hex(0xFFFF00), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_AAButton7, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_AALabel7 = lv_label_create(ui_AAButton7);
lv_obj_set_width( ui_AALabel7, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_AALabel7, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_AALabel7, LV_ALIGN_CENTER );
lv_label_set_text(ui_AALabel7,"7");
lv_obj_set_style_text_color(ui_AALabel7, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_AALabel7, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_AALabel7, &lv_font_montserrat_48, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_AAButton8 = lv_btn_create(ui_AlarmArmed);
lv_obj_set_width( ui_AAButton8, 80);
lv_obj_set_height( ui_AAButton8, 80);
lv_obj_set_x( ui_AAButton8, 0 );
lv_obj_set_y( ui_AAButton8, 218 );
lv_obj_set_align( ui_AAButton8, LV_ALIGN_TOP_MID );
lv_obj_add_flag( ui_AAButton8, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_AAButton8, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_AAButton8, lv_color_hex(0xFFFF00), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_AAButton8, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_AALabel8 = lv_label_create(ui_AAButton8);
lv_obj_set_width( ui_AALabel8, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_AALabel8, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_AALabel8, LV_ALIGN_CENTER );
lv_label_set_text(ui_AALabel8,"8");
lv_obj_set_style_text_color(ui_AALabel8, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_AALabel8, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_AALabel8, &lv_font_montserrat_48, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_AAButton9 = lv_btn_create(ui_AlarmArmed);
lv_obj_set_width( ui_AAButton9, 80);
lv_obj_set_height( ui_AAButton9, 80);
lv_obj_set_x( ui_AAButton9, 90 );
lv_obj_set_y( ui_AAButton9, 218 );
lv_obj_set_align( ui_AAButton9, LV_ALIGN_TOP_MID );
lv_obj_add_flag( ui_AAButton9, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_AAButton9, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_AAButton9, lv_color_hex(0xFFFF00), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_AAButton9, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_AALabel9 = lv_label_create(ui_AAButton9);
lv_obj_set_width( ui_AALabel9, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_AALabel9, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_AALabel9, LV_ALIGN_CENTER );
lv_label_set_text(ui_AALabel9,"9");
lv_obj_set_style_text_color(ui_AALabel9, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_AALabel9, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_AALabel9, &lv_font_montserrat_48, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_AAButtonClear = lv_btn_create(ui_AlarmArmed);
lv_obj_set_width( ui_AAButtonClear, 80);
lv_obj_set_height( ui_AAButtonClear, 80);
lv_obj_set_x( ui_AAButtonClear, -90 );
lv_obj_set_y( ui_AAButtonClear, 303 );
lv_obj_set_align( ui_AAButtonClear, LV_ALIGN_TOP_MID );
lv_obj_add_flag( ui_AAButtonClear, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_AAButtonClear, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_AAButtonClear, lv_color_hex(0xFFFF00), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_AAButtonClear, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_AALabel10 = lv_label_create(ui_AAButtonClear);
lv_obj_set_width( ui_AALabel10, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_AALabel10, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_AALabel10, LV_ALIGN_CENTER );
lv_label_set_text(ui_AALabel10,"__");
lv_obj_set_style_text_color(ui_AALabel10, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_AALabel10, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_AALabel10, &lv_font_montserrat_48, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_AAButton0 = lv_btn_create(ui_AlarmArmed);
lv_obj_set_width( ui_AAButton0, 80);
lv_obj_set_height( ui_AAButton0, 80);
lv_obj_set_x( ui_AAButton0, 0 );
lv_obj_set_y( ui_AAButton0, 303 );
lv_obj_set_align( ui_AAButton0, LV_ALIGN_TOP_MID );
lv_obj_add_flag( ui_AAButton0, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_AAButton0, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_AAButton0, lv_color_hex(0xFFFF00), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_AAButton0, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_AALabel0 = lv_label_create(ui_AAButton0);
lv_obj_set_width( ui_AALabel0, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_AALabel0, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_AALabel0, LV_ALIGN_CENTER );
lv_label_set_text(ui_AALabel0,"0");
lv_obj_set_style_text_color(ui_AALabel0, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_AALabel0, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_AALabel0, &lv_font_montserrat_48, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_AAButtonEnter = lv_btn_create(ui_AlarmArmed);
lv_obj_set_width( ui_AAButtonEnter, 80);
lv_obj_set_height( ui_AAButtonEnter, 80);
lv_obj_set_x( ui_AAButtonEnter, 90 );
lv_obj_set_y( ui_AAButtonEnter, 303 );
lv_obj_set_align( ui_AAButtonEnter, LV_ALIGN_TOP_MID );
lv_obj_add_flag( ui_AAButtonEnter, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_AAButtonEnter, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_AAButtonEnter, lv_color_hex(0xFFFF00), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_AAButtonEnter, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_AALabelEnter = lv_label_create(ui_AAButtonEnter);
lv_obj_set_width( ui_AALabelEnter, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_AALabelEnter, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_AALabelEnter, LV_ALIGN_CENTER );
lv_label_set_text(ui_AALabelEnter,"#");
lv_obj_set_style_text_color(ui_AALabelEnter, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_AALabelEnter, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_AALabelEnter, &lv_font_montserrat_48, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_AALabelAlarmActive = lv_label_create(ui_AlarmArmed);
lv_obj_set_width( ui_AALabelAlarmActive, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_AALabelAlarmActive, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_AALabelAlarmActive, 0 );
lv_obj_set_y( ui_AALabelAlarmActive, 6 );
lv_obj_set_align( ui_AALabelAlarmActive, LV_ALIGN_TOP_MID );
lv_label_set_text(ui_AALabelAlarmActive,"Enter Disarm Code");
lv_obj_set_style_text_color(ui_AALabelAlarmActive, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_AALabelAlarmActive, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_AALabelAlarmActive, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_AALabelAlarmActive, &lv_font_montserrat_32, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_radius(ui_AALabelAlarmActive, 8, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_AALabelAlarmActive, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_AALabelAlarmActive, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_color(ui_AALabelAlarmActive, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_main_stop(ui_AALabelAlarmActive, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_stop(ui_AALabelAlarmActive, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_dir(ui_AALabelAlarmActive, LV_GRAD_DIR_VER, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_AALabelAlarmTrippedOn = lv_label_create(ui_AlarmArmed);
lv_obj_set_width( ui_AALabelAlarmTrippedOn, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_AALabelAlarmTrippedOn, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_AALabelAlarmTrippedOn, 0 );
lv_obj_set_y( ui_AALabelAlarmTrippedOn, -6 );
lv_obj_set_align( ui_AALabelAlarmTrippedOn, LV_ALIGN_BOTTOM_MID );
lv_label_set_text(ui_AALabelAlarmTrippedOn,"  Alarm Tripped  ");
lv_obj_set_style_text_color(ui_AALabelAlarmTrippedOn, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_AALabelAlarmTrippedOn, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_AALabelAlarmTrippedOn, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_AALabelAlarmTrippedOn, &lv_font_montserrat_32, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_radius(ui_AALabelAlarmTrippedOn, 8, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_AALabelAlarmTrippedOn, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_AALabelAlarmTrippedOn, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_color(ui_AALabelAlarmTrippedOn, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_main_stop(ui_AALabelAlarmTrippedOn, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_stop(ui_AALabelAlarmTrippedOn, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_dir(ui_AALabelAlarmTrippedOn, LV_GRAD_DIR_VER, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_AALabelAlarmTrippedOff = lv_label_create(ui_AlarmArmed);
lv_obj_set_width( ui_AALabelAlarmTrippedOff, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_AALabelAlarmTrippedOff, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_AALabelAlarmTrippedOff, 0 );
lv_obj_set_y( ui_AALabelAlarmTrippedOff, -6 );
lv_obj_set_align( ui_AALabelAlarmTrippedOff, LV_ALIGN_BOTTOM_MID );
lv_label_set_text(ui_AALabelAlarmTrippedOff,"  Alarm Active  ");
lv_obj_set_style_text_color(ui_AALabelAlarmTrippedOff, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_AALabelAlarmTrippedOff, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_AALabelAlarmTrippedOff, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_AALabelAlarmTrippedOff, &lv_font_montserrat_32, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_radius(ui_AALabelAlarmTrippedOff, 8, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_AALabelAlarmTrippedOff, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_AALabelAlarmTrippedOff, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_color(ui_AALabelAlarmTrippedOff, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_main_stop(ui_AALabelAlarmTrippedOff, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_stop(ui_AALabelAlarmTrippedOff, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_dir(ui_AALabelAlarmTrippedOff, LV_GRAD_DIR_VER, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_AALabelEnteredPasscode = lv_label_create(ui_AlarmArmed);
lv_obj_set_width( ui_AALabelEnteredPasscode, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_AALabelEnteredPasscode, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_AALabelEnteredPasscode, 0 );
lv_obj_set_y( ui_AALabelEnteredPasscode, -48 );
lv_obj_set_align( ui_AALabelEnteredPasscode, LV_ALIGN_BOTTOM_MID );
lv_label_set_text(ui_AALabelEnteredPasscode,"0000");

lv_obj_add_event_cb(ui_AAButton1, ui_event_AAButton1, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_AAButton2, ui_event_AAButton2, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_AAButton3, ui_event_AAButton3, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_AAButton4, ui_event_AAButton4, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_AAButton5, ui_event_AAButton5, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_AAButton6, ui_event_AAButton6, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_AAButton7, ui_event_AAButton7, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_AAButton8, ui_event_AAButton8, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_AAButton9, ui_event_AAButton9, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_AAButtonClear, ui_event_AAButtonClear, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_AAButton0, ui_event_AAButton0, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_AAButtonEnter, ui_event_AAButtonEnter, LV_EVENT_ALL, NULL);

}
