// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.2
// LVGL version: 8.3.6
// Project name: wt32-sc01-test1-SquareLine_Project

#include "../ui.h"

void ui_AlarmSet_screen_init(void)
{
ui_AlarmSet = lv_obj_create(NULL);
lv_obj_clear_flag( ui_AlarmSet, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_AlarmSet, lv_color_hex(0x002000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_AlarmSet, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ASButton1 = lv_btn_create(ui_AlarmSet);
lv_obj_set_width( ui_ASButton1, 80);
lv_obj_set_height( ui_ASButton1, 80);
lv_obj_set_x( ui_ASButton1, -90 );
lv_obj_set_y( ui_ASButton1, 48 );
lv_obj_set_align( ui_ASButton1, LV_ALIGN_TOP_MID );
lv_obj_add_flag( ui_ASButton1, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_ASButton1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_ASButton1, lv_color_hex(0x0000FF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_ASButton1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_AALabel11 = lv_label_create(ui_ASButton1);
lv_obj_set_width( ui_AALabel11, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_AALabel11, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_AALabel11, LV_ALIGN_CENTER );
lv_label_set_text(ui_AALabel11,"1");
lv_obj_set_style_text_color(ui_AALabel11, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_AALabel11, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_AALabel11, &lv_font_montserrat_48, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ASButton2 = lv_btn_create(ui_AlarmSet);
lv_obj_set_width( ui_ASButton2, 80);
lv_obj_set_height( ui_ASButton2, 80);
lv_obj_set_x( ui_ASButton2, 0 );
lv_obj_set_y( ui_ASButton2, 48 );
lv_obj_set_align( ui_ASButton2, LV_ALIGN_TOP_MID );
lv_obj_add_flag( ui_ASButton2, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_ASButton2, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_ASButton2, lv_color_hex(0x0000FF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_ASButton2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_AALabel12 = lv_label_create(ui_ASButton2);
lv_obj_set_width( ui_AALabel12, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_AALabel12, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_AALabel12, LV_ALIGN_CENTER );
lv_label_set_text(ui_AALabel12,"2");
lv_obj_set_style_text_color(ui_AALabel12, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_AALabel12, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_AALabel12, &lv_font_montserrat_48, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ASButton3 = lv_btn_create(ui_AlarmSet);
lv_obj_set_width( ui_ASButton3, 80);
lv_obj_set_height( ui_ASButton3, 80);
lv_obj_set_x( ui_ASButton3, 90 );
lv_obj_set_y( ui_ASButton3, 48 );
lv_obj_set_align( ui_ASButton3, LV_ALIGN_TOP_MID );
lv_obj_add_flag( ui_ASButton3, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_ASButton3, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_ASButton3, lv_color_hex(0x0000FF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_ASButton3, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_AALabel13 = lv_label_create(ui_ASButton3);
lv_obj_set_width( ui_AALabel13, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_AALabel13, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_AALabel13, LV_ALIGN_CENTER );
lv_label_set_text(ui_AALabel13,"3");
lv_obj_set_style_text_color(ui_AALabel13, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_AALabel13, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_AALabel13, &lv_font_montserrat_48, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ASButton4 = lv_btn_create(ui_AlarmSet);
lv_obj_set_width( ui_ASButton4, 80);
lv_obj_set_height( ui_ASButton4, 80);
lv_obj_set_x( ui_ASButton4, -90 );
lv_obj_set_y( ui_ASButton4, 133 );
lv_obj_set_align( ui_ASButton4, LV_ALIGN_TOP_MID );
lv_obj_add_flag( ui_ASButton4, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_ASButton4, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_ASButton4, lv_color_hex(0x0000FF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_ASButton4, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_AALabel14 = lv_label_create(ui_ASButton4);
lv_obj_set_width( ui_AALabel14, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_AALabel14, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_AALabel14, LV_ALIGN_CENTER );
lv_label_set_text(ui_AALabel14,"4");
lv_obj_set_style_text_color(ui_AALabel14, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_AALabel14, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_AALabel14, &lv_font_montserrat_48, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ASButton5 = lv_btn_create(ui_AlarmSet);
lv_obj_set_width( ui_ASButton5, 80);
lv_obj_set_height( ui_ASButton5, 80);
lv_obj_set_x( ui_ASButton5, 0 );
lv_obj_set_y( ui_ASButton5, 133 );
lv_obj_set_align( ui_ASButton5, LV_ALIGN_TOP_MID );
lv_obj_add_flag( ui_ASButton5, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_ASButton5, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_ASButton5, lv_color_hex(0x0000FF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_ASButton5, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_AALabel15 = lv_label_create(ui_ASButton5);
lv_obj_set_width( ui_AALabel15, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_AALabel15, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_AALabel15, LV_ALIGN_CENTER );
lv_label_set_text(ui_AALabel15,"5");
lv_obj_set_style_text_color(ui_AALabel15, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_AALabel15, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_AALabel15, &lv_font_montserrat_48, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ASButton6 = lv_btn_create(ui_AlarmSet);
lv_obj_set_width( ui_ASButton6, 80);
lv_obj_set_height( ui_ASButton6, 80);
lv_obj_set_x( ui_ASButton6, 90 );
lv_obj_set_y( ui_ASButton6, 133 );
lv_obj_set_align( ui_ASButton6, LV_ALIGN_TOP_MID );
lv_obj_add_flag( ui_ASButton6, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_ASButton6, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_ASButton6, lv_color_hex(0x0000FF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_ASButton6, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_AALabel16 = lv_label_create(ui_ASButton6);
lv_obj_set_width( ui_AALabel16, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_AALabel16, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_AALabel16, LV_ALIGN_CENTER );
lv_label_set_text(ui_AALabel16,"6");
lv_obj_set_style_text_color(ui_AALabel16, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_AALabel16, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_AALabel16, &lv_font_montserrat_48, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ASButton7 = lv_btn_create(ui_AlarmSet);
lv_obj_set_width( ui_ASButton7, 80);
lv_obj_set_height( ui_ASButton7, 80);
lv_obj_set_x( ui_ASButton7, -90 );
lv_obj_set_y( ui_ASButton7, 218 );
lv_obj_set_align( ui_ASButton7, LV_ALIGN_TOP_MID );
lv_obj_add_flag( ui_ASButton7, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_ASButton7, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_ASButton7, lv_color_hex(0x0000FF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_ASButton7, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_AALabel17 = lv_label_create(ui_ASButton7);
lv_obj_set_width( ui_AALabel17, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_AALabel17, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_AALabel17, LV_ALIGN_CENTER );
lv_label_set_text(ui_AALabel17,"7");
lv_obj_set_style_text_color(ui_AALabel17, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_AALabel17, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_AALabel17, &lv_font_montserrat_48, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ASButton8 = lv_btn_create(ui_AlarmSet);
lv_obj_set_width( ui_ASButton8, 80);
lv_obj_set_height( ui_ASButton8, 80);
lv_obj_set_x( ui_ASButton8, 0 );
lv_obj_set_y( ui_ASButton8, 218 );
lv_obj_set_align( ui_ASButton8, LV_ALIGN_TOP_MID );
lv_obj_add_flag( ui_ASButton8, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_ASButton8, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_ASButton8, lv_color_hex(0x0000FF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_ASButton8, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_AALabel18 = lv_label_create(ui_ASButton8);
lv_obj_set_width( ui_AALabel18, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_AALabel18, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_AALabel18, LV_ALIGN_CENTER );
lv_label_set_text(ui_AALabel18,"8");
lv_obj_set_style_text_color(ui_AALabel18, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_AALabel18, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_AALabel18, &lv_font_montserrat_48, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ASButton9 = lv_btn_create(ui_AlarmSet);
lv_obj_set_width( ui_ASButton9, 80);
lv_obj_set_height( ui_ASButton9, 80);
lv_obj_set_x( ui_ASButton9, 90 );
lv_obj_set_y( ui_ASButton9, 218 );
lv_obj_set_align( ui_ASButton9, LV_ALIGN_TOP_MID );
lv_obj_add_flag( ui_ASButton9, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_ASButton9, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_ASButton9, lv_color_hex(0x0000FF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_ASButton9, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_AALabel19 = lv_label_create(ui_ASButton9);
lv_obj_set_width( ui_AALabel19, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_AALabel19, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_AALabel19, LV_ALIGN_CENTER );
lv_label_set_text(ui_AALabel19,"9");
lv_obj_set_style_text_color(ui_AALabel19, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_AALabel19, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_AALabel19, &lv_font_montserrat_48, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ASButtonClear = lv_btn_create(ui_AlarmSet);
lv_obj_set_width( ui_ASButtonClear, 80);
lv_obj_set_height( ui_ASButtonClear, 80);
lv_obj_set_x( ui_ASButtonClear, -90 );
lv_obj_set_y( ui_ASButtonClear, 303 );
lv_obj_set_align( ui_ASButtonClear, LV_ALIGN_TOP_MID );
lv_obj_add_flag( ui_ASButtonClear, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_ASButtonClear, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_ASButtonClear, lv_color_hex(0x0000FF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_ASButtonClear, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_AALabel20 = lv_label_create(ui_ASButtonClear);
lv_obj_set_width( ui_AALabel20, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_AALabel20, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_AALabel20, LV_ALIGN_CENTER );
lv_label_set_text(ui_AALabel20,"__");
lv_obj_set_style_text_color(ui_AALabel20, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_AALabel20, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_AALabel20, &lv_font_montserrat_48, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ASButton0 = lv_btn_create(ui_AlarmSet);
lv_obj_set_width( ui_ASButton0, 80);
lv_obj_set_height( ui_ASButton0, 80);
lv_obj_set_x( ui_ASButton0, 0 );
lv_obj_set_y( ui_ASButton0, 303 );
lv_obj_set_align( ui_ASButton0, LV_ALIGN_TOP_MID );
lv_obj_add_flag( ui_ASButton0, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_ASButton0, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_ASButton0, lv_color_hex(0x0000FF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_ASButton0, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_AALabel21 = lv_label_create(ui_ASButton0);
lv_obj_set_width( ui_AALabel21, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_AALabel21, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_AALabel21, LV_ALIGN_CENTER );
lv_label_set_text(ui_AALabel21,"0");
lv_obj_set_style_text_color(ui_AALabel21, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_AALabel21, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_AALabel21, &lv_font_montserrat_48, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ASButtonEnter = lv_btn_create(ui_AlarmSet);
lv_obj_set_width( ui_ASButtonEnter, 80);
lv_obj_set_height( ui_ASButtonEnter, 80);
lv_obj_set_x( ui_ASButtonEnter, 90 );
lv_obj_set_y( ui_ASButtonEnter, 303 );
lv_obj_set_align( ui_ASButtonEnter, LV_ALIGN_TOP_MID );
lv_obj_add_flag( ui_ASButtonEnter, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_ASButtonEnter, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_ASButtonEnter, lv_color_hex(0x0000FF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_ASButtonEnter, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_AALabelEnter1 = lv_label_create(ui_ASButtonEnter);
lv_obj_set_width( ui_AALabelEnter1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_AALabelEnter1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_AALabelEnter1, LV_ALIGN_CENTER );
lv_label_set_text(ui_AALabelEnter1,"#");
lv_obj_set_style_text_color(ui_AALabelEnter1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_AALabelEnter1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_AALabelEnter1, &lv_font_montserrat_48, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ASLabelAlarmSetTop = lv_label_create(ui_AlarmSet);
lv_obj_set_width( ui_ASLabelAlarmSetTop, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_ASLabelAlarmSetTop, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_ASLabelAlarmSetTop, 0 );
lv_obj_set_y( ui_ASLabelAlarmSetTop, 6 );
lv_obj_set_align( ui_ASLabelAlarmSetTop, LV_ALIGN_TOP_MID );
lv_label_set_text(ui_ASLabelAlarmSetTop,"Enter Arm Code / Enter Code");
lv_obj_set_style_text_color(ui_ASLabelAlarmSetTop, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_ASLabelAlarmSetTop, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_ASLabelAlarmSetTop, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_ASLabelAlarmSetTop, &lv_font_montserrat_32, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_radius(ui_ASLabelAlarmSetTop, 8, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_ASLabelAlarmSetTop, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_ASLabelAlarmSetTop, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_color(ui_ASLabelAlarmSetTop, lv_color_hex(0x00FF00), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_main_stop(ui_ASLabelAlarmSetTop, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_stop(ui_ASLabelAlarmSetTop, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_dir(ui_ASLabelAlarmSetTop, LV_GRAD_DIR_VER, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_remove_AALabelAlarmTrippedOn1 = lv_label_create(ui_AlarmSet);
lv_obj_set_width( ui_remove_AALabelAlarmTrippedOn1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_remove_AALabelAlarmTrippedOn1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_remove_AALabelAlarmTrippedOn1, 0 );
lv_obj_set_y( ui_remove_AALabelAlarmTrippedOn1, -6 );
lv_obj_set_align( ui_remove_AALabelAlarmTrippedOn1, LV_ALIGN_BOTTOM_MID );
lv_label_set_text(ui_remove_AALabelAlarmTrippedOn1,"  Alarm Tripped  ");
lv_obj_add_flag( ui_remove_AALabelAlarmTrippedOn1, LV_OBJ_FLAG_HIDDEN );   /// Flags
lv_obj_set_style_text_color(ui_remove_AALabelAlarmTrippedOn1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_remove_AALabelAlarmTrippedOn1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_remove_AALabelAlarmTrippedOn1, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_remove_AALabelAlarmTrippedOn1, &lv_font_montserrat_32, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_radius(ui_remove_AALabelAlarmTrippedOn1, 8, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_remove_AALabelAlarmTrippedOn1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_remove_AALabelAlarmTrippedOn1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_color(ui_remove_AALabelAlarmTrippedOn1, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_main_stop(ui_remove_AALabelAlarmTrippedOn1, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_stop(ui_remove_AALabelAlarmTrippedOn1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_dir(ui_remove_AALabelAlarmTrippedOn1, LV_GRAD_DIR_VER, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_remove_AALabelAlarmTrippedOff1 = lv_label_create(ui_AlarmSet);
lv_obj_set_width( ui_remove_AALabelAlarmTrippedOff1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_remove_AALabelAlarmTrippedOff1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_remove_AALabelAlarmTrippedOff1, 0 );
lv_obj_set_y( ui_remove_AALabelAlarmTrippedOff1, -6 );
lv_obj_set_align( ui_remove_AALabelAlarmTrippedOff1, LV_ALIGN_BOTTOM_MID );
lv_label_set_text(ui_remove_AALabelAlarmTrippedOff1,"  Alarm Active  ");
lv_obj_add_flag( ui_remove_AALabelAlarmTrippedOff1, LV_OBJ_FLAG_HIDDEN );   /// Flags
lv_obj_set_style_text_color(ui_remove_AALabelAlarmTrippedOff1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_remove_AALabelAlarmTrippedOff1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_remove_AALabelAlarmTrippedOff1, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_remove_AALabelAlarmTrippedOff1, &lv_font_montserrat_32, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_radius(ui_remove_AALabelAlarmTrippedOff1, 8, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_remove_AALabelAlarmTrippedOff1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_remove_AALabelAlarmTrippedOff1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_color(ui_remove_AALabelAlarmTrippedOff1, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_main_stop(ui_remove_AALabelAlarmTrippedOff1, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_stop(ui_remove_AALabelAlarmTrippedOff1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_dir(ui_remove_AALabelAlarmTrippedOff1, LV_GRAD_DIR_VER, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ASLabelEnteredPasscode = lv_label_create(ui_AlarmSet);
lv_obj_set_width( ui_ASLabelEnteredPasscode, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_ASLabelEnteredPasscode, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_ASLabelEnteredPasscode, 0 );
lv_obj_set_y( ui_ASLabelEnteredPasscode, -48 );
lv_obj_set_align( ui_ASLabelEnteredPasscode, LV_ALIGN_BOTTOM_MID );
lv_label_set_text(ui_ASLabelEnteredPasscode,"0000");
lv_obj_add_flag( ui_ASLabelEnteredPasscode, LV_OBJ_FLAG_HIDDEN );   /// Flags

ui_ASPanelScanLine = lv_obj_create(ui_AlarmSet);
lv_obj_set_width( ui_ASPanelScanLine, 320);
lv_obj_set_height( ui_ASPanelScanLine, 2);
lv_obj_set_align( ui_ASPanelScanLine, LV_ALIGN_TOP_MID );
lv_obj_clear_flag( ui_ASPanelScanLine, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_ASPanelScanLine, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_ASPanelScanLine, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_outline_color(ui_ASPanelScanLine, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_outline_opa(ui_ASPanelScanLine, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_outline_width(ui_ASPanelScanLine, 2, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_outline_pad(ui_ASPanelScanLine, 2, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ASLabelEnterNewGuestCode = lv_label_create(ui_AlarmSet);
lv_obj_set_width( ui_ASLabelEnterNewGuestCode, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_ASLabelEnterNewGuestCode, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_ASLabelEnterNewGuestCode, 0 );
lv_obj_set_y( ui_ASLabelEnterNewGuestCode, -46 );
lv_obj_set_align( ui_ASLabelEnterNewGuestCode, LV_ALIGN_BOTTOM_MID );
lv_label_set_text(ui_ASLabelEnterNewGuestCode,"Original / Set New");
lv_obj_set_style_text_color(ui_ASLabelEnterNewGuestCode, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_ASLabelEnterNewGuestCode, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_ASLabelEnterNewGuestCode, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_ASLabelEnterNewGuestCode, &lv_font_montserrat_32, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_radius(ui_ASLabelEnterNewGuestCode, 8, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_ASLabelEnterNewGuestCode, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_ASLabelEnterNewGuestCode, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_color(ui_ASLabelEnterNewGuestCode, lv_color_hex(0x00FF00), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_main_stop(ui_ASLabelEnterNewGuestCode, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_stop(ui_ASLabelEnterNewGuestCode, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_dir(ui_ASLabelEnterNewGuestCode, LV_GRAD_DIR_VER, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ASLabelEnterNewGuestCode1 = lv_label_create(ui_AlarmSet);
lv_obj_set_width( ui_ASLabelEnterNewGuestCode1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_ASLabelEnterNewGuestCode1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_ASLabelEnterNewGuestCode1, 0 );
lv_obj_set_y( ui_ASLabelEnterNewGuestCode1, -6 );
lv_obj_set_align( ui_ASLabelEnterNewGuestCode1, LV_ALIGN_BOTTOM_MID );
lv_label_set_text(ui_ASLabelEnterNewGuestCode1,"Admin / Guest 1 / Guest 2");
lv_obj_set_style_text_color(ui_ASLabelEnterNewGuestCode1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_ASLabelEnterNewGuestCode1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_ASLabelEnterNewGuestCode1, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_ASLabelEnterNewGuestCode1, &lv_font_montserrat_32, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_radius(ui_ASLabelEnterNewGuestCode1, 8, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_ASLabelEnterNewGuestCode1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_ASLabelEnterNewGuestCode1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_color(ui_ASLabelEnterNewGuestCode1, lv_color_hex(0x00FF00), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_main_stop(ui_ASLabelEnterNewGuestCode1, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_stop(ui_ASLabelEnterNewGuestCode1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_dir(ui_ASLabelEnterNewGuestCode1, LV_GRAD_DIR_VER, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ASButtonBack = lv_btn_create(ui_AlarmSet);
lv_obj_set_width( ui_ASButtonBack, 60);
lv_obj_set_height( ui_ASButtonBack, 60);
lv_obj_set_align( ui_ASButtonBack, LV_ALIGN_BOTTOM_LEFT );
lv_obj_add_flag( ui_ASButtonBack, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_ASButtonBack, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_ASButtonBack, lv_color_hex(0x0000FF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_ASButtonBack, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ASBack = lv_label_create(ui_ASButtonBack);
lv_obj_set_width( ui_ASBack, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_ASBack, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_ASBack, LV_ALIGN_CENTER );
lv_label_set_text(ui_ASBack,"<");
lv_obj_set_style_text_color(ui_ASBack, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_ASBack, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_ASBack, &lv_font_montserrat_48, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_add_event_cb(ui_ASButton1, ui_event_ASButton1, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_ASButton2, ui_event_ASButton2, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_ASButton3, ui_event_ASButton3, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_ASButton4, ui_event_ASButton4, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_ASButton5, ui_event_ASButton5, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_ASButton6, ui_event_ASButton6, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_ASButton7, ui_event_ASButton7, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_ASButton8, ui_event_ASButton8, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_ASButton9, ui_event_ASButton9, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_ASButtonClear, ui_event_ASButtonClear, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_ASButton0, ui_event_ASButton0, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_ASButtonEnter, ui_event_ASButtonEnter, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_ASButtonBack, ui_event_ASButtonBack, LV_EVENT_ALL, NULL);

}
