// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.2
// LVGL version: 8.3.6
// Project name: wt32-sc01-test1-SquareLine_Project

#include "../ui.h"

void ui_ChooseCode_screen_init(void)
{
ui_ChooseCode = lv_obj_create(NULL);
lv_obj_clear_flag( ui_ChooseCode, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_ChooseCode, lv_color_hex(0x002000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_ChooseCode, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_CCButtonAdmin = lv_btn_create(ui_ChooseCode);
lv_obj_set_width( ui_CCButtonAdmin, 200);
lv_obj_set_height( ui_CCButtonAdmin, 80);
lv_obj_set_x( ui_CCButtonAdmin, 0 );
lv_obj_set_y( ui_CCButtonAdmin, 48 );
lv_obj_set_align( ui_CCButtonAdmin, LV_ALIGN_TOP_MID );
lv_obj_add_flag( ui_CCButtonAdmin, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_CCButtonAdmin, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_CCButtonAdmin, lv_color_hex(0x0000FF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_CCButtonAdmin, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_CCLabelAdmin = lv_label_create(ui_CCButtonAdmin);
lv_obj_set_width( ui_CCLabelAdmin, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_CCLabelAdmin, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_CCLabelAdmin, LV_ALIGN_CENTER );
lv_label_set_text(ui_CCLabelAdmin,"Admin");
lv_obj_set_style_text_color(ui_CCLabelAdmin, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_CCLabelAdmin, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_CCLabelAdmin, &lv_font_montserrat_48, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_CCButtonGuest1 = lv_btn_create(ui_ChooseCode);
lv_obj_set_width( ui_CCButtonGuest1, 200);
lv_obj_set_height( ui_CCButtonGuest1, 80);
lv_obj_set_x( ui_CCButtonGuest1, 0 );
lv_obj_set_y( ui_CCButtonGuest1, 133 );
lv_obj_set_align( ui_CCButtonGuest1, LV_ALIGN_TOP_MID );
lv_obj_add_flag( ui_CCButtonGuest1, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_CCButtonGuest1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_CCButtonGuest1, lv_color_hex(0x0000FF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_CCButtonGuest1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_CCLabelGuest1 = lv_label_create(ui_CCButtonGuest1);
lv_obj_set_width( ui_CCLabelGuest1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_CCLabelGuest1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_CCLabelGuest1, LV_ALIGN_CENTER );
lv_label_set_text(ui_CCLabelGuest1,"Guest 1");
lv_obj_set_style_text_color(ui_CCLabelGuest1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_CCLabelGuest1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_CCLabelGuest1, &lv_font_montserrat_48, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_CCButtonGuest2 = lv_btn_create(ui_ChooseCode);
lv_obj_set_width( ui_CCButtonGuest2, 200);
lv_obj_set_height( ui_CCButtonGuest2, 80);
lv_obj_set_x( ui_CCButtonGuest2, 0 );
lv_obj_set_y( ui_CCButtonGuest2, 218 );
lv_obj_set_align( ui_CCButtonGuest2, LV_ALIGN_TOP_MID );
lv_obj_add_flag( ui_CCButtonGuest2, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_CCButtonGuest2, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_CCButtonGuest2, lv_color_hex(0x0000FF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_CCButtonGuest2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_CCLabelGuest2 = lv_label_create(ui_CCButtonGuest2);
lv_obj_set_width( ui_CCLabelGuest2, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_CCLabelGuest2, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_CCLabelGuest2, LV_ALIGN_CENTER );
lv_label_set_text(ui_CCLabelGuest2,"Guest 2");
lv_obj_set_style_text_color(ui_CCLabelGuest2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_CCLabelGuest2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_CCLabelGuest2, &lv_font_montserrat_48, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_CCButtonBack = lv_btn_create(ui_ChooseCode);
lv_obj_set_width( ui_CCButtonBack, 60);
lv_obj_set_height( ui_CCButtonBack, 60);
lv_obj_set_align( ui_CCButtonBack, LV_ALIGN_BOTTOM_LEFT );
lv_obj_add_flag( ui_CCButtonBack, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_CCButtonBack, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_CCButtonBack, lv_color_hex(0x0000FF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_CCButtonBack, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_CCBack = lv_label_create(ui_CCButtonBack);
lv_obj_set_width( ui_CCBack, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_CCBack, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_CCBack, LV_ALIGN_CENTER );
lv_label_set_text(ui_CCBack,"<");
lv_obj_set_style_text_color(ui_CCBack, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_CCBack, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_CCBack, &lv_font_montserrat_48, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_CCLabelChoseCode = lv_label_create(ui_ChooseCode);
lv_obj_set_width( ui_CCLabelChoseCode, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_CCLabelChoseCode, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_CCLabelChoseCode, 0 );
lv_obj_set_y( ui_CCLabelChoseCode, 6 );
lv_obj_set_align( ui_CCLabelChoseCode, LV_ALIGN_TOP_MID );
lv_label_set_text(ui_CCLabelChoseCode,"Choose Code");
lv_obj_set_style_text_color(ui_CCLabelChoseCode, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_CCLabelChoseCode, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_CCLabelChoseCode, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_CCLabelChoseCode, &lv_font_montserrat_32, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_radius(ui_CCLabelChoseCode, 8, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_CCLabelChoseCode, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_CCLabelChoseCode, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_color(ui_CCLabelChoseCode, lv_color_hex(0x00FF00), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_main_stop(ui_CCLabelChoseCode, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_stop(ui_CCLabelChoseCode, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_dir(ui_CCLabelChoseCode, LV_GRAD_DIR_VER, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_CCLabelChooseCode = lv_label_create(ui_ChooseCode);
lv_obj_set_width( ui_CCLabelChooseCode, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_CCLabelChooseCode, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_CCLabelChooseCode, 0 );
lv_obj_set_y( ui_CCLabelChooseCode, -66 );
lv_obj_set_align( ui_CCLabelChooseCode, LV_ALIGN_BOTTOM_MID );
lv_label_set_text(ui_CCLabelChooseCode,"Choose Code \nto Change");
lv_obj_set_style_text_color(ui_CCLabelChooseCode, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_CCLabelChooseCode, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_CCLabelChooseCode, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_CCLabelChooseCode, &lv_font_montserrat_32, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_radius(ui_CCLabelChooseCode, 8, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_CCLabelChooseCode, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_CCLabelChooseCode, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_color(ui_CCLabelChooseCode, lv_color_hex(0x00FF00), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_main_stop(ui_CCLabelChooseCode, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_stop(ui_CCLabelChooseCode, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_dir(ui_CCLabelChooseCode, LV_GRAD_DIR_VER, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_remove_CCLabelEnterNewGuestCode3 = lv_label_create(ui_ChooseCode);
lv_obj_set_width( ui_remove_CCLabelEnterNewGuestCode3, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_remove_CCLabelEnterNewGuestCode3, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_remove_CCLabelEnterNewGuestCode3, 0 );
lv_obj_set_y( ui_remove_CCLabelEnterNewGuestCode3, -6 );
lv_obj_set_align( ui_remove_CCLabelEnterNewGuestCode3, LV_ALIGN_BOTTOM_MID );
lv_label_set_text(ui_remove_CCLabelEnterNewGuestCode3,"Guest 1");
lv_obj_add_flag( ui_remove_CCLabelEnterNewGuestCode3, LV_OBJ_FLAG_HIDDEN );   /// Flags
lv_obj_set_style_text_color(ui_remove_CCLabelEnterNewGuestCode3, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_remove_CCLabelEnterNewGuestCode3, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_remove_CCLabelEnterNewGuestCode3, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_remove_CCLabelEnterNewGuestCode3, &lv_font_montserrat_32, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_radius(ui_remove_CCLabelEnterNewGuestCode3, 8, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_remove_CCLabelEnterNewGuestCode3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_remove_CCLabelEnterNewGuestCode3, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_color(ui_remove_CCLabelEnterNewGuestCode3, lv_color_hex(0x00FF00), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_main_stop(ui_remove_CCLabelEnterNewGuestCode3, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_stop(ui_remove_CCLabelEnterNewGuestCode3, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_dir(ui_remove_CCLabelEnterNewGuestCode3, LV_GRAD_DIR_VER, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_add_event_cb(ui_CCButtonAdmin, ui_event_CCButtonAdmin, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_CCButtonGuest1, ui_event_CCButtonGuest1, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_CCButtonGuest2, ui_event_CCButtonGuest2, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_CCButtonBack, ui_event_CCButtonBack, LV_EVENT_ALL, NULL);

}
