// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.2
// LVGL version: 8.3.6
// Project name: wt32-sc01-test1-SquareLine_Project

#include "../ui.h"

void ui_MainMenu_screen_init(void)
{
ui_MainMenu = lv_obj_create(NULL);
lv_obj_clear_flag( ui_MainMenu, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_MainMenu, lv_color_hex(0x002000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_MainMenu, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_MMButtonSetAlarm = lv_btn_create(ui_MainMenu);
lv_obj_set_width( ui_MMButtonSetAlarm, 300);
lv_obj_set_height( ui_MMButtonSetAlarm, 80);
lv_obj_set_x( ui_MMButtonSetAlarm, 0 );
lv_obj_set_y( ui_MMButtonSetAlarm, 48 );
lv_obj_set_align( ui_MMButtonSetAlarm, LV_ALIGN_TOP_MID );
lv_obj_add_flag( ui_MMButtonSetAlarm, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_MMButtonSetAlarm, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_MMButtonSetAlarm, lv_color_hex(0x0000FF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_MMButtonSetAlarm, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_MMLabelSetAlarm = lv_label_create(ui_MMButtonSetAlarm);
lv_obj_set_width( ui_MMLabelSetAlarm, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_MMLabelSetAlarm, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_MMLabelSetAlarm, LV_ALIGN_CENTER );
lv_label_set_text(ui_MMLabelSetAlarm,"Set Alarm");
lv_obj_set_style_text_color(ui_MMLabelSetAlarm, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_MMLabelSetAlarm, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_MMLabelSetAlarm, &lv_font_montserrat_48, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_MMButtonSettings = lv_btn_create(ui_MainMenu);
lv_obj_set_width( ui_MMButtonSettings, 300);
lv_obj_set_height( ui_MMButtonSettings, 80);
lv_obj_set_x( ui_MMButtonSettings, 0 );
lv_obj_set_y( ui_MMButtonSettings, 133 );
lv_obj_set_align( ui_MMButtonSettings, LV_ALIGN_TOP_MID );
lv_obj_add_flag( ui_MMButtonSettings, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_MMButtonSettings, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_MMButtonSettings, lv_color_hex(0x0000FF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_MMButtonSettings, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_MMLabelSettings = lv_label_create(ui_MMButtonSettings);
lv_obj_set_width( ui_MMLabelSettings, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_MMLabelSettings, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_MMLabelSettings, LV_ALIGN_CENTER );
lv_label_set_text(ui_MMLabelSettings,"Settings");
lv_obj_set_style_text_color(ui_MMLabelSettings, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_MMLabelSettings, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_MMLabelSettings, &lv_font_montserrat_48, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_MMButtonChangeCode = lv_btn_create(ui_MainMenu);
lv_obj_set_width( ui_MMButtonChangeCode, 300);
lv_obj_set_height( ui_MMButtonChangeCode, 80);
lv_obj_set_x( ui_MMButtonChangeCode, 0 );
lv_obj_set_y( ui_MMButtonChangeCode, 218 );
lv_obj_set_align( ui_MMButtonChangeCode, LV_ALIGN_TOP_MID );
lv_obj_add_flag( ui_MMButtonChangeCode, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_MMButtonChangeCode, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_MMButtonChangeCode, lv_color_hex(0x0000FF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_MMButtonChangeCode, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_MMLabelChangeCode = lv_label_create(ui_MMButtonChangeCode);
lv_obj_set_width( ui_MMLabelChangeCode, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_MMLabelChangeCode, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_MMLabelChangeCode, LV_ALIGN_CENTER );
lv_label_set_text(ui_MMLabelChangeCode,"Edit Code");
lv_obj_set_style_text_color(ui_MMLabelChangeCode, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_MMLabelChangeCode, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_MMLabelChangeCode, &lv_font_montserrat_48, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_MMButtonBack = lv_btn_create(ui_MainMenu);
lv_obj_set_width( ui_MMButtonBack, 60);
lv_obj_set_height( ui_MMButtonBack, 60);
lv_obj_set_align( ui_MMButtonBack, LV_ALIGN_BOTTOM_LEFT );
lv_obj_add_flag( ui_MMButtonBack, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_MMButtonBack, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_MMButtonBack, lv_color_hex(0x0000FF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_MMButtonBack, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_MMBack = lv_label_create(ui_MMButtonBack);
lv_obj_set_width( ui_MMBack, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_MMBack, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_MMBack, LV_ALIGN_CENTER );
lv_label_set_text(ui_MMBack,"<");
lv_obj_set_style_text_color(ui_MMBack, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_MMBack, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_MMBack, &lv_font_montserrat_48, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_MMLabelMenu = lv_label_create(ui_MainMenu);
lv_obj_set_width( ui_MMLabelMenu, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_MMLabelMenu, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_MMLabelMenu, 0 );
lv_obj_set_y( ui_MMLabelMenu, 6 );
lv_obj_set_align( ui_MMLabelMenu, LV_ALIGN_TOP_MID );
lv_label_set_text(ui_MMLabelMenu,"Menu");
lv_obj_set_style_text_color(ui_MMLabelMenu, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_MMLabelMenu, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_MMLabelMenu, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_MMLabelMenu, &lv_font_montserrat_32, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_radius(ui_MMLabelMenu, 8, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_MMLabelMenu, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_MMLabelMenu, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_color(ui_MMLabelMenu, lv_color_hex(0x00FF00), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_main_stop(ui_MMLabelMenu, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_stop(ui_MMLabelMenu, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_dir(ui_MMLabelMenu, LV_GRAD_DIR_VER, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_removeCCLabelChooseCode1 = lv_label_create(ui_MainMenu);
lv_obj_set_width( ui_removeCCLabelChooseCode1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_removeCCLabelChooseCode1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_removeCCLabelChooseCode1, 0 );
lv_obj_set_y( ui_removeCCLabelChooseCode1, -66 );
lv_obj_set_align( ui_removeCCLabelChooseCode1, LV_ALIGN_BOTTOM_MID );
lv_label_set_text(ui_removeCCLabelChooseCode1,"Choose Code \nto Change");
lv_obj_add_flag( ui_removeCCLabelChooseCode1, LV_OBJ_FLAG_HIDDEN );   /// Flags
lv_obj_set_style_text_color(ui_removeCCLabelChooseCode1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_removeCCLabelChooseCode1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_removeCCLabelChooseCode1, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_removeCCLabelChooseCode1, &lv_font_montserrat_32, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_radius(ui_removeCCLabelChooseCode1, 8, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_removeCCLabelChooseCode1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_removeCCLabelChooseCode1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_color(ui_removeCCLabelChooseCode1, lv_color_hex(0x00FF00), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_main_stop(ui_removeCCLabelChooseCode1, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_stop(ui_removeCCLabelChooseCode1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_dir(ui_removeCCLabelChooseCode1, LV_GRAD_DIR_VER, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_remove_CCLabelEnterNewGuestCode1 = lv_label_create(ui_MainMenu);
lv_obj_set_width( ui_remove_CCLabelEnterNewGuestCode1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_remove_CCLabelEnterNewGuestCode1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_remove_CCLabelEnterNewGuestCode1, 0 );
lv_obj_set_y( ui_remove_CCLabelEnterNewGuestCode1, -6 );
lv_obj_set_align( ui_remove_CCLabelEnterNewGuestCode1, LV_ALIGN_BOTTOM_MID );
lv_label_set_text(ui_remove_CCLabelEnterNewGuestCode1,"Guest 1");
lv_obj_add_flag( ui_remove_CCLabelEnterNewGuestCode1, LV_OBJ_FLAG_HIDDEN );   /// Flags
lv_obj_set_style_text_color(ui_remove_CCLabelEnterNewGuestCode1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_remove_CCLabelEnterNewGuestCode1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_remove_CCLabelEnterNewGuestCode1, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_remove_CCLabelEnterNewGuestCode1, &lv_font_montserrat_32, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_radius(ui_remove_CCLabelEnterNewGuestCode1, 8, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_remove_CCLabelEnterNewGuestCode1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_remove_CCLabelEnterNewGuestCode1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_color(ui_remove_CCLabelEnterNewGuestCode1, lv_color_hex(0x00FF00), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_main_stop(ui_remove_CCLabelEnterNewGuestCode1, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_stop(ui_remove_CCLabelEnterNewGuestCode1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_dir(ui_remove_CCLabelEnterNewGuestCode1, LV_GRAD_DIR_VER, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_add_event_cb(ui_MMButtonSetAlarm, ui_event_MMButtonSetAlarm, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_MMButtonSettings, ui_event_MMButtonSettings, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_MMButtonChangeCode, ui_event_MMButtonChangeCode, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_MMButtonBack, ui_event_MMButtonBack, LV_EVENT_ALL, NULL);

}
